WC now initializes fingerprint according to config only
descope/descope-js pull request #301
Opened 2023-11-07 08:37 UTC by itaihanski

## Related Issues

https://github.com/descope/etc/issues/4307

## Description

**web-component breaking change**: web-component now initializes fingerprint according to the `flow-config` as opposed to the now removed `telemetryKey`. When enabled, the flow config will contain the required public key to enable calculating device fingerprints.
To facilitate this change `web-js` was updated to expose the needed functions to dynamically enable fingerprint through the flow-config. The `web-js` behavior is not changed.

## Must

- [X] Tests
- [X] Documentation (if applicable)

2023-11-13 16:46 UTC, meirwah commented
@nirgur @tomerlichtash can you review ?

2023-11-14 11:51 UTC, tomerlichtash commented on packages/web-component/src/lib/descope-wc/DescopeWc.ts
> +        flowConfig.fingerprintKey?.length > 0
`flowConfig.fingerprintKey`

2023-11-14 11:58 UTC, tomerlichtash commented on packages/web-js-sdk/src/enhancers/withFingerprint/index.ts
> +      return createSdk({
return createSdk(config);

2023-11-14 12:06 UTC, tomerlichtash requested changes
Add few comments

2023-11-14 14:14 UTC, tomerlichtash approved these changes

2023-11-14 14:14 UTC, merged